project_id = "tcrymcryokttnzozvdyk"

[api]
enabled = true
port = 54321

[auth]
enabled = true
external_phone_enabled = false
external_email_enabled = true
external_apple_enabled = false
external_azure_enabled = false
external_bitbucket_enabled = false
external_discord_enabled = false
external_facebook_enabled = false
external_figma_enabled = false
external_github_enabled = false
external_gitlab_enabled = false
external_google_enabled = false
external_keycloak_enabled = false
external_linkedin_enabled = false
external_notion_enabled = false
external_twitch_enabled = false
external_twitter_enabled = false
external_slack_enabled = false
external_spotify_enabled = false
external_workos_enabled = false
external_zoom_enabled = false
external_kakao_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.google-oauth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = true